In [1]:
# The csv file is imported as a data frame through Pandas
import pandas as pd

In [2]:
Musicinfo_df = pd.read_csv("music_info_chosenattributes.csv")
Musicinfo_df.head(5)

,Unnamed: 0,name,artist,danceability,energy,key,mode,valence,tempo,similarity_to_MrBrightside,X_vector
0,0,Mr. Brightside,The Killers,0.355,0.918,1,1,0.240,0.619996,1.000000,"[0.355, 0.918, 1, 1, 0.24, 0.6199962326545135]"
1,1,Wonderwall,Oasis,0.409,0.892,2,1,0.651,0.730137,0.733143,"[0.409, 0.892, 2, 1, 0.651, 0.7301366709223718]"
2,2,Come as You Are,Nirvana,0.508,0.826,4,0,0.543,0.502363,0.555728,"[0.508, 0.826, 4, 0, 0.543, 0.5023629628079282]"
3,3,Take Me Out,Franz Ferdinand,0.279,0.664,9,1,0.490,0.437682,0.706281,"[0.279, 0.664, 9, 1, 0.49, 0.4376818267439671]"
4,4,Creep,Radiohead,0.515,0.430,7,1,0.104,0.384441,0.663407,"[0.515, 0.43, 7, 1, 0.104, 0.3844408631407104]"

In [3]:
# Get rid of two unnecessary columns
Reduced_Musicinfo_df = Musicinfo_df.drop(columns = ['similarity_to_MrBrightside','X_vector'])

In [4]:
Reduced_Musicinfo_df.head(5)

,Unnamed: 0,name,artist,danceability,energy,key,mode,valence,tempo
0,0,Mr. Brightside,The Killers,0.355,0.918,1,1,0.240,0.619996
1,1,Wonderwall,Oasis,0.409,0.892,2,1,0.651,0.730137
2,2,Come as You Are,Nirvana,0.508,0.826,4,0,0.543,0.502363
3,3,Take Me Out,Franz Ferdinand,0.279,0.664,9,1,0.490,0.437682
4,4,Creep,Radiohead,0.515,0.430,7,1,0.104,0.384441

In [5]:
# Import the K-means class from the clusters module in Scikit-learn
from sklearn.cluster import KMeans

In [6]:
# Define the inputs we will use for our K-means clustering algorithm
X = Reduced_Musicinfo_df[['danceability','energy','key','mode','valence','tempo']].copy()

In [7]:
# Finally, let's fit/assign clusters to each of the data points in the data frame 
kmeans = KMeans(n_clusters=3)
y = kmeans.fit_predict(Reduced_Musicinfo_df[['danceability','energy','key','mode','valence','tempo']])
Reduced_Musicinfo_df['Cluster'] = y
print(Reduced_Musicinfo_df.head())

   Unnamed: 0             name           artist  danceability  energy  key  \
0           0   Mr. Brightside      The Killers         0.355   0.918    1
1           1       Wonderwall            Oasis         0.409   0.892    2
2           2  Come as You Are          Nirvana         0.508   0.826    4
3           3      Take Me Out  Franz Ferdinand         0.279   0.664    9
4           4            Creep        Radiohead         0.515   0.430    7

   mode  valence     tempo  Cluster
0     1    0.240  0.619996        1
1     1    0.651  0.730137        1
2     0    0.543  0.502363        1
3     1    0.490  0.437682        2
4     1    0.104  0.384441        0

In [8]:
Reduced_Musicinfo_df.head(4)

,Unnamed: 0,name,artist,danceability,energy,key,mode,valence,tempo,Cluster
0,0,Mr. Brightside,The Killers,0.355,0.918,1,1,0.240,0.619996,1
1,1,Wonderwall,Oasis,0.409,0.892,2,1,0.651,0.730137,1
2,2,Come as You Are,Nirvana,0.508,0.826,4,0,0.543,0.502363,1
3,3,Take Me Out,Franz Ferdinand,0.279,0.664,9,1,0.490,0.437682,2

In [9]:
# write the previous data frame to a csv file 
Reduced_Musicinfo_df.to_csv("3clusters_musicinfo.csv",index=False)